USE ROLE ACCOUNTADMIN;

-- API integration is needed for GitHub integration
CREATE OR REPLACE API INTEGRATION GIT_INTEGRATION_REEVES
API_PROVIDER = GIT_HTTPS_API
API_ALLOWED_PREFIXES = ('https://github.com/reeves-ah') -- INSERT YOUR GITHUB USERNAME HERE
ENABLED = TRUE;

GRANT USAGE ON INTEGRATION GIT_INTEGRATION_REEVES TO ROLE SYSADMIN; 


-- To monitor data pipeline's completion
CREATE OR REPLACE NOTIFICATION INTEGRATION EMAIL_INTEGRATION
TYPE=EMAIL
ENABLED=TRUE;

GRANT USAGE ON INTEGRATION EMAIL_INTEGRATION TO ROLE SYSADMIN; 

USE ROLE SYSADMIN;

CREATE OR REPLACE WAREHOUSE WH_DATAOPS_XSM
WITH WAREHOUSE_SIZE = 'XSMALL' 
     AUTO_SUSPEND = 60 
     AUTO_RESUME = TRUE
     MIN_CLUSTER_COUNT = 1
     MAX_CLUSTER_COUNT = 1
     SCALING_POLICY = 'ECONOMY'
     INITIALLY_SUSPENDED = TRUE
;